FROM golang:1.25 AS build
WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/docai-service ./main.go

FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=build /out/docai-service /docai-service

ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["/docai-service"]
